### ISSUE TITLE
v3.0.0 does not work

### ISSUE THREAD

**Issue by Andrew-Chen-Wang** [pre-commit/action#174]
Reverting to 2.0.3 works

Yaml file:

```yaml
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Lint
      uses: pre-commit/action@v3.0.0
```

Traceback:

```
Run pre-commit/action@v3.0.0
Run python -m pip install pre-commit
Collecting pre-commit
  Downloading pre_commit-3.0.2-py2.py3-none-any.whl (202 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 202.3/202.3 kB 3.8 MB/s eta 0:00:00
Collecting virtualenv>=20.10.0
  Downloading virtualenv-20.17.1-py3-none-any.whl (8.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.8/8.8 MB 93.0 MB/s eta 0:00:00
Collecting identify>=1.0.0
  Downloading identify-2.5.17-py2.py3-none-any.whl (98 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.7/98.7 kB 18.5 MB/s eta 0:00:00
Collecting cfgv>=2.0.0
  Downloading cfgv-3.3.1-py2.py3-none-any.whl (7.3 kB)
Collecting nodeenv>=0.[11](https://github.com/LazifyAI/dashboard-api/actions/runs/4057175955/jobs/6982597943#step:4:12).1
  Downloading nodeenv-1.7.0-py2.py3-none-any.whl ([21](https://github.com/LazifyAI/dashboard-api/actions/runs/4057175955/jobs/6982597943#step:4:23) kB)
Collecting pyyaml>=5.1
  Downloading PyYAML-6.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (682 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 682.2/682.2 kB 72.8 MB/s eta 0:00:00
Requirement already satisfied: setuptools in /opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages (from nodeenv>=0.11.1->pre-commit) (65.5.0)
Collecting filelock<4,>=3.4.1
  Downloading filelock-3.9.0-py3-none-any.whl (9.7 kB)
Collecting distlib<1,>=0.3.6
  Downloading distlib-0.3.6-py2.py3-none-any.whl (468 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 468.5/468.5 kB 67.7 MB/s eta 0:00:00
Collecting platformdirs<3,>=2.4
  Downloading platformdirs-2.6.2-py3-none-any.whl (14 kB)
Installing collected packages: distlib, pyyaml, platformdirs, nodeenv, identify, filelock, cfgv, virtualenv, pre-commit
Successfully installed cfgv-3.3.1 distlib-0.3.6 filelock-3.9.0 identify-2.5.17 nodeenv-1.7.0 platformdirs-2.6.2 pre-commit-3.0.2 pyyaml-6.0 virtualenv-20.17.1

Notice:  A new release of pip available: [22](https://github.com/LazifyAI/dashboard-api/actions/runs/4057175955/jobs/6982597943#step:4:24).3.1 -> [23](https://github.com/LazifyAI/dashboard-api/actions/runs/4057175955/jobs/6982597943#step:4:25).0
Notice:  To update, run: pip install --upgrade pip
Run python -m pip freeze --local
cfgv==3.3.1
distlib==0.3.6
filelock==3.9.0
identify==2.5.17
nodeenv==1.7.0
platformdirs==2.6.2
pre-commit==3.0.2
PyYAML==6.0
virtualenv==20.17.1
Run actions/cache@v3
Cache not found for input keys: pre-commit-3|/opt/hostedtoolcache/Python/3.10.9/x64|b82ae7d389[27](https://github.com/LazifyAI/dashboard-api/actions/runs/4057175955/jobs/6982597943#step:4:29)63bc15d739b0750af9f0f8988905f321e593772a1f5c033232[28](https://github.com/LazifyAI/dashboard-api/actions/runs/4057175955/jobs/6982597943#step:4:30)
Run pre-commit run --show-diff-on-failure --color=always --all-files
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/asottile/pyupgrade.
[INFO] Initializing environment for https://github.com/psf/black.
[INFO] Initializing environment for https://github.com/PyCQA/isort.
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/asottile/pyupgrade.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/psf/black.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/PyCQA/isort.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/home/runner/.cache/pre-commit/repo6rq1iirh/py_env-python3/bin/python', '-mpip', 'install', '.')
return code: 1
stdout:
    Processing /home/runner/.cache/pre-commit/repo6rq1iirh
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'done'
      Preparing metadata (pyproject.toml): started
      Preparing metadata (pyproject.toml): finished with status 'error'
    
stderr:
      error: subprocess-exited-with-error
      
      × Preparing metadata (pyproject.toml) did not run successfully.
      │ exit code: 1
      ╰─> [14 lines of output]
          Traceback (most recent call last):
            File "/home/runner/.cache/pre-commit/repo6rq1iirh/py_env-python3/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
              main()
            File "/home/runner/.cache/pre-commit/repo6rq1iirh/py_env-python3/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line [33](https://github.com/LazifyAI/dashboard-api/actions/runs/4057175955/jobs/6982597943#step:4:35)3, in main
              json_out['return_val'] = hook(**hook_input['kwargs'])
            File "/home/runner/.cache/pre-commit/repo6rq1iirh/py_env-python3/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
              return hook(metadata_directory, config_settings)
            File "/tmp/pip-build-env-mr7wpsc6/overlay/lib/python3.10/site-packages/poetry/core/masonry/api.py", line [40](https://github.com/LazifyAI/dashboard-api/actions/runs/4057175955/jobs/6982597943#step:4:42), in prepare_metadata_for_build_wheel
              poetry = Factory().create_poetry(Path(".").resolve(), with_groups=False)
            File "/tmp/pip-build-env-mr7wpsc6/overlay/lib/python3.10/site-packages/poetry/core/factory.py", line 57, in create_poetry
              raise RuntimeError("The Poetry configuration is invalid:\n" + message)
          RuntimeError: The Poetry configuration is invalid:
            - [extras.pipfile_deprecated_finder.2] 'pip-shims<=0.3.4' does not match '^[a-zA-Z-_.0-9]+$'
          
          [end of output]
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: metadata-generation-failed
    
    × Encountered error while generating package metadata.
    ╰─> See above for output.
    
    note: This is an issue with the package mentioned above, not pip.
    hint: See above for details.
    
Check the log at /home/runner/.cache/pre-commit/pre-commit.log
```

**Comment by asottile** [comment]
you must be hitting a cache with 2.0.3 -- your error is unrelated to the action version -- please google your error message next time
