### ISSUE TITLE
error on using cache:  No module named 'setuptools'

### ISSUE THREAD

**Issue by yelizariev** [pre-commit/action#9]
# Logs
https://github.com/it-projects-llc/pos-addons/pull/1200/checks?check_run_id=438932879
```

isort except __init__.py.................................................Failed
- hook id: isort
- exit code: 1

Traceback (most recent call last):
  File "/home/runner/.cache/pre-commit/repoov996k65/py_env-python3/bin/isort", line 5, in <module>
    from isort.main import main
  File "/home/runner/.cache/pre-commit/repoov996k65/py_env-python3/lib/python3.7/site-packages/isort/main.py", line 29, in <module>
    import setuptools
ModuleNotFoundError: No module named 'setuptools'
Traceback (most recent call last):
  File "/home/runner/.cache/pre-commit/repoov996k65/py_env-python3/bin/isort", line 5, in <module>
    from isort.main import main
  File "/home/runner/.cache/pre-commit/repoov996k65/py_env-python3/lib/python3.7/site-packages/isort/main.py", line 29, in <module>
    import setuptools
ModuleNotFoundError: No module named 'setuptools'
```

# Possible Solution

Add extra step to install setuptools?

```
jobs:
  pre-commit:
    name: "pre-commit"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: "3.7.x"
      - uses: Install not cached dependencies
        run: |
          pip install setuptools
      - name: Check Python Version
        run:
          echo "::set-env name=PY::$(python --version --version | sha256sum | cut -d' '
          -f1)"
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}
      - uses: pre-commit/action@v1.0.1
```

I didn't test it yet

**Comment by asottile** [comment]
this is related to virtualenv 20 breakage, #4 has a workaround -- I'm hoping to convince virtualenv to make the default better though

**Comment by asottile** [comment]
this should be fixed now without the need of a workaround via `virtualenv` 20.0.2

**Comment by yelizariev** [comment]
Thanks for the information. Does pre-commit uses latest version of virtualenv? If not, does it mean that extra step is need to upgrade it?

```
      - uses: actions/setup-python@v1
        with:
          python-version: "3.7.x"
      - uses: Upgrade virtualenv
        run: |
          pip install virtualenv>=20.0.2
     ....
```

**Comment by yelizariev** [comment]
I'd just try it without asking, but somehow cache is not always used and I cannot check the possible solution

**Comment by asottile** [comment]
it should use the latest, if your cache is poisoned you may need to change the cache key, it should be as simple as adding some string to it (such as a 2)
